"""Ensure all tables created

Revision ID: 0974efa58833
Revises: 59aa167237ae
Create Date: 2025-12-28 10:03:52.734787

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0974efa58833"
down_revision: Union[str, Sequence[str], None] = "59aa167237ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
