"""Add WebOrder and Customer Models

Revision ID: 59aa167237ae
Revises: 5c9b110c4188
Create Date: 2025-12-28 09:31:04.158061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59aa167237ae"
down_revision: Union[str, Sequence[str], None] = "5c9b110c4188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cedula", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_cedula"), "customers", ["cedula"], unique=True)
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_table(
        "web_order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("web_order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("price_usd", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["web_order_id"],
            ["web_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_web_order_items_id"), "web_order_items", ["id"], unique=False
    )
    op.add_column("web_orders", sa.Column("customer_id", sa.Integer(), nullable=True))
    op.add_column("web_orders", sa.Column("customer_data", sa.JSON(), nullable=False))
    op.add_column("web_orders", sa.Column("payment_method", sa.String(), nullable=True))
    op.add_column(
        "web_orders", sa.Column("payment_proof_url", sa.String(), nullable=True)
    )
    op.add_column(
        "web_orders", sa.Column("transaction_ref", sa.String(), nullable=True)
    )
    op.alter_column(
        "web_orders",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "APPROVED", "REJECTED", name="weborderstatus"
        ),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "web_orders",
        "total_estimated_usd",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.create_foreign_key(None, "web_orders", "customers", ["customer_id"], ["id"])
    op.drop_column("web_orders", "customer_contact")
    op.drop_column("web_orders", "customer_name")
    op.drop_column("web_orders", "items_json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "web_orders",
        sa.Column("items_json", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "web_orders",
        sa.Column("customer_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "web_orders",
        sa.Column(
            "customer_contact", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "web_orders", type_="foreignkey")
    op.alter_column(
        "web_orders",
        "total_estimated_usd",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "web_orders",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM("PENDING", "APPROVED", "REJECTED", name="weborderstatus"),
        existing_nullable=True,
    )
    op.drop_column("web_orders", "transaction_ref")
    op.drop_column("web_orders", "payment_proof_url")
    op.drop_column("web_orders", "payment_method")
    op.drop_column("web_orders", "customer_data")
    op.drop_column("web_orders", "customer_id")
    op.drop_index(op.f("ix_web_order_items_id"), table_name="web_order_items")
    op.drop_table("web_order_items")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_cedula"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
