"""fix_product_boolean_and_add_roles

Revision ID: 5c9b110c4188
Revises: cde7714510c1
Create Date: 2025-12-28 08:56:56.578218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c9b110c4188"
down_revision: Union[str, Sequence[str], None] = "cde7714510c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums manually with idempotent SQL (Postgres specific)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE userrole AS ENUM ('ADMIN', 'WORKER');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE weborderstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    op.create_table(
        "web_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column("customer_contact", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="weborderstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("total_estimated_usd", sa.Float(), nullable=True),
        sa.Column("items_json", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_web_orders_id"), "web_orders", ["id"], unique=False)
    op.add_column("products", sa.Column("is_public", sa.Boolean(), nullable=True))
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM("ADMIN", "WORKER", name="userrole", create_type=False),
        nullable=False,
        postgresql_using="role::userrole",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum("ADMIN", "WORKER", name="userrole"),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("products", "is_public")
    op.drop_index(op.f("ix_web_orders_id"), table_name="web_orders")
    op.drop_table("web_orders")
    # ### end Alembic commands ###
